### ISSUE TITLE
Guide to running the example

### ISSUE THREAD

**Issue by rooi** [AndyQ/NFCPassportReader#18]
Hi,

Could you please provide a guide for building and running the example? I tried using iOS 13, but the example app does not seem to respond the inputs. Did I build it wrong, or am I using the incorrect inputs?

Thanks!

Roy

**Comment by mickeyl** [comment]
Same problem here. After entering the details, nothing happens and I can't seem to get the 'Scan Passport' button(?) to appear. Moreover, what's the purpose of the UISegmentedControl?

**Comment by leo1988joseph** [comment]
Hi @mickeyl , any progress yet? I am in desperate need of the code now. Could you guide me?

**Comment by mickeyl** [comment]
I didn't pursue this further, I hope @AndyQ will chime in. That said, did you check whether the Info.plist contains the necessary tag IDs for passport reading? After doing what https://stackoverflow.com/a/56516232/415982 told, reading (not decrypting though) worked in my example program.

**Comment by AndyQ** [comment]
Something changed in one of the iOS 13 beta which stopped textfield updating the model.
This was fixed in 1.0.5 (just realised I hadn't pushed the podspec! - done!).

Hopefully now the UI should correctly update (you need at least 8 chars for the passport number and valid dates for both - yymmdd format).

If you are still having issues please let me know!

**Comment by leo1988joseph** [comment]
Hi, we have been given an expired passport to test with form the client. I
just want to know wether the code could actually fetch the data from the
NFC chip of passport. Which line in the code should I comment so that I can
at-least know the values of the passport are read correctly? (iOS Swift)

Thanks and regards
Leo Joseph

**Comment by AndyQ** [comment]
@leo1988joseph All passports are treated equally - from a NFC Reading perspective, there is no difference between an expired passport and an non-expired passport.  It is down to the implementor to check if a passport has expired and handle that accordingly.

It may be that the passive authentication may fail if the certificate used to sign the passport had also expired (or is no longer included in the master list) but thats not necessarily the case (but again the implementor needs to explicitly check for this)

**Comment by AndyQ** [comment]
Closing as assuming this is now fixed

**Comment by leo1988joseph** [comment]
Hi AndyQ,

While using the NFCReader in some of the US passports, we are getting a
flickering screen as shown in the video attached. Can I please know were
exactly in the code you have written to not read certain kind of passports?
It din't read some Canadian passports too. Kindly help.

Thanks and regards
Leo Joseph

**Comment by AndyQ** [comment]
Hi Leo,  there is nothing in the code that blocks certain passports.  There may be (are) incompatibilities with some passports - especially some older ones,as it appears that there were many ways of implementing the e-passport chips.

Unfortunately there is no video attached so I can't see what your issue was.  If you could raise a new issue for this that would be great.

**Comment by leo1988joseph** [comment]
Hi Andy,

This is the video I was saying.

Please have a look. Just see is this issue worth a new bug?

Regards
Leo Joseph

**Comment by AndyQ** [comment]
Hi Leo, unfortunately as this issue is closed I don't think attached files get added

**Comment by leo1988joseph** [comment]
How can i forward the video to you?

Can you give me some other way by which i can forward it to you?

**Comment by AndyQ** [comment]
Can you please open a new issue?

**Comment by leo1988joseph** [comment]
I am getting some error while creating a new issue.

Can you for now give me some medium by which I can just share the video to
show what I meant by flickering? Its bit urgent.

Regards

**Comment by AndyQ** [comment]
You can send me a the video directly - my email is in my profile
